name: Build Lock EXE 32+64-bit

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64, x86]  # x64 = 64-bit, x86 = 32-bit

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        architecture: ${{ matrix.arch }}

    - name: Install dependencies
      run: |
        pip install pyinstaller keyboard pywin32

    - name: Build EXE
      run: |
        pyinstaller --onefile Lock.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: lock-${{ matrix.arch }}
        path: dist/Lock.exe
